// <auto-generated />
using System;
using MedicalEquipmentSupplySystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalEquipmentSupplySystem.DataAccess.Migrations
{
    [DbContext(typeof(MedicalEquipmentSupplySystemDbContext))]
    [Migration("20231107075708_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SupplyCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SupplyCompanyId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.EquipmentReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyAdministratorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalWorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyAdministratorId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("HospitalWorkerId");

                    b.ToTable("EquipmentReservation");
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.SupplyCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("SupplyCompanies");
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Address"), "utf8mb4");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.CompanyAdministrator", b =>
                {
                    b.HasBaseType("MedicalEquipmentSupplySystem.DataAccess.Model.User");

                    b.Property<int?>("SupplyCompanyId")
                        .HasColumnType("int");

                    b.HasIndex("SupplyCompanyId");

                    b.ToTable("CompanyAdministrators", (string)null);
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.HospitalWorker", b =>
                {
                    b.HasBaseType("MedicalEquipmentSupplySystem.DataAccess.Model.User");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Penalties")
                        .HasColumnType("int");

                    b.ToTable("HospitalWorkers", (string)null);
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.SystemAdministrator", b =>
                {
                    b.HasBaseType("MedicalEquipmentSupplySystem.DataAccess.Model.User");

                    b.ToTable("SystemAdministrators", (string)null);
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.Equipment", b =>
                {
                    b.HasOne("MedicalEquipmentSupplySystem.DataAccess.Model.SupplyCompany", "SupplyCompany")
                        .WithMany("equipmentList")
                        .HasForeignKey("SupplyCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplyCompany");
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.EquipmentReservation", b =>
                {
                    b.HasOne("MedicalEquipmentSupplySystem.DataAccess.Model.CompanyAdministrator", "CompanyAdministrator")
                        .WithMany()
                        .HasForeignKey("CompanyAdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalEquipmentSupplySystem.DataAccess.Model.Equipment", "Equipment")
                        .WithMany("equipmentReservations")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalEquipmentSupplySystem.DataAccess.Model.HospitalWorker", "HospitalWorker")
                        .WithMany("EquipmentReservationList")
                        .HasForeignKey("HospitalWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyAdministrator");

                    b.Navigation("Equipment");

                    b.Navigation("HospitalWorker");
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.CompanyAdministrator", b =>
                {
                    b.HasOne("MedicalEquipmentSupplySystem.DataAccess.Model.User", null)
                        .WithOne()
                        .HasForeignKey("MedicalEquipmentSupplySystem.DataAccess.Model.CompanyAdministrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalEquipmentSupplySystem.DataAccess.Model.SupplyCompany", null)
                        .WithMany("companyAdministrators")
                        .HasForeignKey("SupplyCompanyId");
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.HospitalWorker", b =>
                {
                    b.HasOne("MedicalEquipmentSupplySystem.DataAccess.Model.User", null)
                        .WithOne()
                        .HasForeignKey("MedicalEquipmentSupplySystem.DataAccess.Model.HospitalWorker", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.SystemAdministrator", b =>
                {
                    b.HasOne("MedicalEquipmentSupplySystem.DataAccess.Model.User", null)
                        .WithOne()
                        .HasForeignKey("MedicalEquipmentSupplySystem.DataAccess.Model.SystemAdministrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.Equipment", b =>
                {
                    b.Navigation("equipmentReservations");
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.SupplyCompany", b =>
                {
                    b.Navigation("companyAdministrators");

                    b.Navigation("equipmentList");
                });

            modelBuilder.Entity("MedicalEquipmentSupplySystem.DataAccess.Model.HospitalWorker", b =>
                {
                    b.Navigation("EquipmentReservationList");
                });
#pragma warning restore 612, 618
        }
    }
}
